# Generated by Django 6.0.1 on 2026-01-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('restaurant_owner', 'Restaurant Owner'), ('platform_admin', 'Platform Admin'), ('super_admin', 'Super Admin')], default='user', max_length=20),
        ),
    ]
