# Generated by manually on 2026-01-24 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
