# Generated by Django 6.0.1 on 2026-02-04 08:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('name_ja', models.CharField(help_text='Japanese name of the allergen', max_length=255)),
                ('allergen_type', models.CharField(choices=[('mandatory', 'Mandatory'), ('recommended', 'Recommended')], max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ingredients',
            name='allergens',
            field=models.ManyToManyField(blank=True, related_name='ingredients', to='restaurants.allergen'),
        ),
        migrations.AddField(
            model_name='menu',
            name='allergens',
            field=models.ManyToManyField(blank=True, related_name='menus', to='restaurants.allergen'),
        ),
    ]
