# Generated by Django 6.0.1 on 2026-02-04 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_seed_japan_allergens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='allergens',
        ),
    ]
